from django.urls import path

from .views import (
    LogTestView,
    PracticeFluency,
    PracticeGrammar,
    PracticePronunication,
    PracticeQuestionEvaluation,
    PracticeQuestionHistory,
    PracticeQuestionView,
    PracticeSnapshot,
    PracticeSummaryStats,
    PracticeVocab,
    PracticeWordOfTheDay,
    SubmitCustomPracticeQuestionView,
    SubmitQuestionView,
    PracticeCoherence,
    PracticeEmotion,
    PracticeReviewResponse,
)

urlpatterns = [
    path('testlog', LogTestView.as_view(), name='log_test_view'),
    path('questions', PracticeQuestionView.as_view(), name='get_practice_questions'),
    path('submit_custom_question', SubmitCustomPracticeQuestionView.as_view(), name='submit_custom_question'),
    path('submit_practice_question_response/<uuid:practice_question_id>', SubmitQuestionView.as_view(), name='submit_practice_question_response'),
    path('question_evaluation/<uuid:practice_question_id>', PracticeQuestionEvaluation.as_view(), name='get_practice_question_evaluation'),
    path('question_history', PracticeQuestionHistory.as_view(), name='get_practice_question_history'),
    path('question_history/<int:user_id>', PracticeQuestionHistory.as_view(), name='get_user_practice_question_history'),
    path('stats_summary', PracticeSummaryStats.as_view(), name='practice_summary_stats'),
    path('last_practice_snapshot', PracticeSnapshot.as_view(), name='last_practice_snapshot'),
    path('eval/fluency/<uuid:practice_question_id>', PracticeFluency.as_view(), name='get_eval_fluency'),
    path('eval/pronunciations/<uuid:practice_question_id>', PracticePronunication.as_view(), name='get_eval_pronunciations'),
    path('eval/grammar/<uuid:practice_question_id>', PracticeGrammar.as_view(), name='get_eval_grammar'),
    path('eval/vocab/<uuid:practice_question_id>', PracticeVocab.as_view(), name='get_eval_vocab'),
    path('word_of_the_day', PracticeWordOfTheDay.as_view(), name='get_word_of_the_day'),
    path('eval/coherence/<uuid:practice_question_id>', PracticeCoherence.as_view(), name='get_eval_coherence'),
    path('eval/emotion/<uuid:practice_question_id>', PracticeEmotion.as_view(), name='get_eval_emotion'),
    path('eval/review_response/<uuid:practice_question_id>', PracticeReviewResponse.as_view(), name='get_review_response'),
]
