version: "3"
services:
  lms:
    build: .
    ports:
      - "8000:8000"
    entrypoint: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/appuser/code
    working_dir: /appuser/code
    env_file:
      - .env

  postgres:
    image: postgres:16
    container_name: postgres-lms
    volumes:
      - pgdb-lms:/var/lib/postgresql/data
    env_file: .env
    ports:
      - 5432:5432

  redis:
    image: redis:7
    container_name: redis-lms
    restart: unless-stopped
    env_file: .env
    command: /bin/sh -c "redis-server --requirepass ${REDIS_PASSWORD}"
    ports:
      - 6379:6379


  lms-notebook-dev:
    container_name: lms-notebook
    image: skylearn-lms:latest
    platform: linux/amd64
    entrypoint: python manage.py shell_plus --notebook -- --ip 0.0.0.0 --port 8000
    restart: unless-stopped
    volumes:
      - .:/home/appuser/code
    working_dir: /home/appuser/code
    ports:
      - "8888:8000"
    env_file:
      - .env
    environment:
      - DJANGO_ALLOW_ASYNC_UNSAFE=true
    depends_on:
      - postgres
      - redis

volumes:
  pgdb-lms:
    external: true
    
