version: "3"
services:
  lms:
    build: .
    ports:
      - "8000:8000"
    entrypoint: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/appuser/code
    working_dir: /appuser/code
    env_file:
      - .env

  postgres:
    image: postgres:16
    container_name: postgres-lms
    volumes:
      - pgdb:/var/lib/postgresql/data
    env_file: .env
    ports:
      - 5432:5432

volumes:
  pgdb:
    external: true
