version: "3"
services:
  lms:
    build: .
    image: ghcr.io/blendnet-ai/django-lms:latest
    platform: linux/amd64
    ports:
      - "8000:8000"
    entrypoint: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/appuser/code
    working_dir: /appuser/code
    env_file:
      - .env

  postgres:
    image: postgres:16
    container_name: postgres-lms
    volumes:
      - pgdb_lms:/var/lib/postgresql/data
    env_file: .env
    ports:
      - 5432:5432

  lms-celery-dev:
    image: ghcr.io/blendnet-ai/django-lms:latest
    platform: linux/amd64
    container_name: lms-celery
    working_dir: appuser/code
    volumes:
      - .:appuser/code
    env_file:
      - .env
    entrypoint: python -m celery -A lms worker -l debug -Q default
    depends_on:
      - redis
      - postgres
  
  redis:
    image: redis:7
    container_name: redis-lms
    restart: unless-stopped
    env_file: .env
    command: /bin/sh -c "redis-server --requirepass ${REDIS_PASSWORD}"
    ports:
      - 6379:6379

volumes:
  pgdb_lms:
    external: true
