# Generated by Django 4.2.16 on 2025-01-24 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [
        # ("course", "0001_initial"),
        # ("course", "0002_course_summary_en_course_summary_ru_course_title_en_and_more"),
        # ("course", "0003_course_summary_es_course_summary_fr_course_title_es_and_more"),
        # ("course", "0004_alter_course_code_alter_course_credit_and_more"),
        # ("course", "0005_course_assessment_generation_ids"),
        # ("course", "0006_course_course_provider_batch_and_more"),
        # ("course", "0007_remove_course_program_remove_upload_file_and_more"),
        # ("course", "0008_remove_courseoffer_dep_head_delete_program_and_more"),
    ]

    initial = True

    dependencies = [
        # ("meetings", "0001_initial"),
        # ("accounts", "0001_initial"),
        # ("core", "0001_initial"),
        # ("accounts", "0003_courseprovider_courseprovideradmin"),
        # ("evaluation", "0001_initial"),
        # ("accounts", "0006_remove_departmenthead_department_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("title", models.CharField(default="Test title", max_length=200)),
                (
                    "code",
                    models.CharField(
                        default="testcode101", max_length=200, unique=True
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, default="Test summary", max_length=200
                    ),
                ),
                (
                    "course_provider",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.courseprovider",
                    ),
                ),
                ("drive_folder_link", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="CourseAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "courses",
                    models.ManyToManyField(
                        related_name="allocated_course", to="course.course"
                    ),
                ),
                (
                    "lecturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocated_lecturer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.course"
                    ),
                ),
                (
                    "lecturer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LiveClassSeriesBatchAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrolled_batches",
                        to="course.batch",
                    ),
                ),
                (
                    "live_class_series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_enrollments",
                        to="meetings.meetingseries",
                    ),
                ),
            ],
            options={
                "unique_together": {("live_class_series", "batch")},
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("order_in_course", models.IntegerField(null=True)),
                (
                    "assignment_configs",
                    models.ManyToManyField(
                        blank=True,
                        related_name="modules",
                        to="evaluation.assessmentgenerationconfig",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules_list",
                        to="course.course",
                    ),
                ),
            ],
            options={
                "unique_together": {("course", "order_in_course")},
            },
        ),
        migrations.CreateModel(
            name="Upload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "upload_time",
                    models.DateTimeField(
                        auto_now_add=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.course"
                    ),
                ),
                ("blob_url", models.CharField(blank=True, max_length=255)),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploads",
                        to="course.module",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UploadVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("summary", models.TextField(blank=True, default="test")),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.course"
                    ),
                ),
                ("blob_url", models.CharField(blank=True, max_length=255)),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_uploads",
                        to="course.module",
                    ),
                ),
            ],
        ),
    ]
