# Generated by Django 4.2.16 on 2025-02-03 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
        ('evaluation', '0001_initial'),
        ('accounts', '0002_initial'),
        ('meetings', '0001_squashed_0003_attendancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='assignment_configs',
            field=models.ManyToManyField(blank=True, related_name='modules', to='evaluation.assessmentgenerationconfig'),
        ),
        migrations.AddField(
            model_name='module',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules_list', to='course.course'),
        ),
        migrations.AddField(
            model_name='liveclassseriesbatchallocation',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_batches', to='course.batch'),
        ),
        migrations.AddField(
            model_name='liveclassseriesbatchallocation',
            name='live_class_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='meetings.meetingseries'),
        ),
        migrations.AddField(
            model_name='courseallocation',
            name='courses',
            field=models.ManyToManyField(related_name='allocated_course', to='course.course'),
        ),
        migrations.AddField(
            model_name='courseallocation',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocated_lecturer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='course_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.courseprovider'),
        ),
        migrations.AddField(
            model_name='batch',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.AddField(
            model_name='batch',
            name='lecturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('course', 'order_in_course')},
        ),
        migrations.AlterUniqueTogether(
            name='liveclassseriesbatchallocation',
            unique_together={('live_class_series', 'batch')},
        ),
    ]
