# Generated by Django 4.2.16 on 2024-11-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_code_alter_course_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='assessment_generation_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
