# Generated by Django 4.2.16 on 2025-01-24 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_courseprovider_teams_guid_and_more"),
        (
            "course",
            "0001_squashed_0008_remove_courseoffer_dep_head_delete_program_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.courseprovider",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="summary",
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="upload",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="upload",
            name="upload_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="uploadvideo",
            name="summary",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="uploadvideo",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
