# Generated by Django 4.2.18 on 2025-07-15 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("course", "0001_initial"),
        ("Feedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseformentry",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="course.batch"
            ),
        ),
        migrations.AddField(
            model_name="courseformentry",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Feedback.feedbackform"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="courseformentry",
            unique_together={("form", "batch", "start_date", "end_date")},
        ),
    ]
