# Generated by Django 4.2.16 on 2024-11-10 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplates',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('prompt', models.TextField(help_text='actual prompt with variables')),
                ('additional_guardrail_prompt', models.TextField(default='', help_text="additional prompt text to be added at end of each user msg for additional guardrails. (This won't be saved in conversation history)")),
                ('type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=100)),
                ('transcript', models.TextField()),
                ('thumbnail', models.URLField(default='')),
                ('timestamped_transcript', models.TextField(default='')),
                ('chapters_data', models.JSONField(default=dict)),
                ('questions_data', models.JSONField(default=dict)),
                ('duration', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserConsumedVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('chapters_data', models.JSONField(default=dict)),
                ('questions_data', models.JSONField(default=dict)),
                ('time_spent', models.IntegerField(default=0)),
                ('quizzes_attempted', models.IntegerField(default=0)),
                ('total_points_scored', models.IntegerField(default=0)),
                ('highlights', models.JSONField(default=dict)),
                ('chat_history', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_count', models.IntegerField(default=0)),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ai_learning.video')),
            ],
            options={
                'unique_together': {('user_id', 'video_id')},
            },
        ),
    ]
