# Generated by Django 4.2.16 on 2024-11-20 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_courseprovider_courseprovideradmin'),
        ('course', '0006_course_course_provider_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batches',
            field=models.ManyToManyField(blank=True, to='course.batch'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_course_provider_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseprovideradmin',
            name='course_provider_admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseprovider',
            name='admins',
            field=models.ManyToManyField(to='accounts.courseprovideradmin'),
        ),
    ]
