# Generated by Django 4.2.16 on 2025-01-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_squashed_0007_delete_departmenthead_delete_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseprovider",
            name="teams_guid",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="courseprovider",
            name="teams_upn",
            field=models.CharField(max_length=100),
        ),
    ]
