# Generated by Django 4.2.16 on 2025-01-24 19:16

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [
        # ("meetings", "0001_initial"),
        # ("meetings", "0002_meeting_attendance_metadata_meeting_blob_url_and_more"),
        # ("meetings", "0003_attendancerecord"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("start_time", models.TimeField()),
                ("duration", models.DurationField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "recurrence_type",
                    models.CharField(
                        choices=[
                            ("not_repeating", "Not Repeating"),
                            ("day", "Daily"),
                            ("week", "Weekly"),
                            ("month", "Monthly"),
                        ],
                        default="not_repeating",
                        max_length=20,
                    ),
                ),
                (
                    "weekday_schedule",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.BooleanField(),
                        blank=True,
                        help_text="Array of 7 booleans representing each weekday",
                        null=True,
                        size=7,
                    ),
                ),
                (
                    "monthly_day",
                    models.IntegerField(
                        blank=True,
                        help_text="Day of month for monthly recurring classes",
                        null=True,
                    ),
                ),
                (
                    "presenter_details",
                    models.JSONField(
                        blank=True,
                        help_text="JSON containing presenter details (guid, name, email)",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Live Class Series",
                "verbose_name_plural": "Live Class Series",
            },
        ),
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                (
                    "title_override",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("start_time_override", models.TimeField(blank=True, null=True)),
                ("duration_override", models.DurationField(blank=True, null=True)),
                ("link", models.URLField(blank=True, max_length=500, null=True)),
                ("first_notification_sent", models.BooleanField(default=False)),
                ("second_notification_sent", models.BooleanField(default=False)),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="meetings.meetingseries",
                    ),
                ),
                ("attendance_metadata", models.JSONField(blank=True, null=True)),
                ("blob_url", models.CharField(blank=True, max_length=200)),
                (
                    "conference_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("conference_metadata", models.JSONField(blank=True, null=True)),
                ("recording_metadata", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Live Class",
                "verbose_name_plural": "Live Classes",
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attendance_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("attendance", models.BooleanField(default=False)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="meetings.meeting",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Record",
                "verbose_name_plural": "Attendance Records",
                "unique_together": {("user_id", "meeting")},
            },
        ),
    ]
