# Generated by Django 4.2.16 on 2024-11-20 06:08

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_time', models.TimeField()),
                ('duration', models.DurationField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('recurrence_type', models.CharField(choices=[('not_repeating', 'Not Repeating'), ('day', 'Daily'), ('week', 'Weekly'), ('month', 'Monthly')], default='not_repeating', max_length=20)),
                ('weekday_schedule', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), blank=True, help_text='Array of 7 booleans representing each weekday', null=True, size=7)),
                ('monthly_day', models.IntegerField(blank=True, help_text='Day of month for monthly recurring classes', null=True)),
            ],
            options={
                'verbose_name': 'Live Class Series',
                'verbose_name_plural': 'Live Class Series',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('title_override', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time_override', models.TimeField(blank=True, null=True)),
                ('duration_override', models.DurationField(blank=True, null=True)),
                ('link', models.URLField()),
                ('first_notification_sent', models.BooleanField(default=False)),
                ('second_notification_sent', models.BooleanField(default=False)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meetingseries')),
            ],
            options={
                'verbose_name': 'Live Class',
                'verbose_name_plural': 'Live Classes',
            },
        ),
    ]
