# Generated by Django 4.2.18 on 2025-07-15 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("teams", "Microsoft Teams"), ("zoom", "Zoom")],
                        default="teams",
                        help_text="Meeting platform provider",
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField()),
                (
                    "title_override",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("start_time_override", models.TimeField(blank=True, null=True)),
                ("duration_override", models.DurationField(blank=True, null=True)),
                ("link", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "conference_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("conference_metadata", models.JSONField(blank=True, null=True)),
                ("first_notification_sent", models.BooleanField(default=False)),
                ("second_notification_sent", models.BooleanField(default=False)),
                ("recording_metadata", models.JSONField(blank=True, null=True)),
                ("attendance_metadata", models.JSONField(blank=True, null=True)),
                ("blob_url", models.CharField(blank=True, max_length=200)),
                (
                    "additional_recordings",
                    models.JSONField(blank=True, default=list, null=True),
                ),
            ],
            options={
                "verbose_name": "Live Class",
                "verbose_name_plural": "Live Classes",
            },
        ),
        migrations.CreateModel(
            name="MeetingSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("start_time", models.TimeField()),
                ("duration", models.DurationField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "recurrence_type",
                    models.CharField(
                        choices=[
                            ("not_repeating", "Not Repeating"),
                            ("day", "Daily"),
                            ("week", "Weekly"),
                            ("month", "Monthly"),
                        ],
                        default="not_repeating",
                        max_length=20,
                    ),
                ),
                (
                    "weekday_schedule",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of 7 booleans representing each weekday",
                        null=True,
                    ),
                ),
                (
                    "monthly_day",
                    models.IntegerField(
                        blank=True,
                        help_text="Day of month for monthly recurring classes",
                        null=True,
                    ),
                ),
                (
                    "presenter_details",
                    models.JSONField(
                        blank=True,
                        help_text="JSON containing presenter details (guid, name, email)",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Live Class Series",
                "verbose_name_plural": "Live Class Series",
            },
        ),
        migrations.CreateModel(
            name="ReferenceMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("url", models.URLField(max_length=512)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reference_materials",
                        to="meetings.meeting",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="meeting",
            name="series",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="meetings.meetingseries"
            ),
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attendance_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("attendance", models.BooleanField(default=False)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="meetings.meeting",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Record",
                "verbose_name_plural": "Attendance Records",
                "unique_together": {("user_id", "meeting")},
            },
        ),
    ]
