# Generated by Django 4.2.18 on 2025-07-16 04:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="referencematerial",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="referencematerial",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="referencematerial",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="reference_materials/"
            ),
        ),
        migrations.AddField(
            model_name="referencematerial",
            name="material_type",
            field=models.CharField(
                choices=[("link", "Link"), ("file", "File")],
                default="link",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="referencematerial",
            name="url",
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
