# Generated by Django 4.2.18 on 2025-07-15 15:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("course", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCourseReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assessment_time",
                    models.DurationField(default=datetime.timedelta(0)),
                ),
                (
                    "resource_time_video",
                    models.DurationField(default=datetime.timedelta(0)),
                ),
                (
                    "resource_time_reading",
                    models.DurationField(default=datetime.timedelta(0)),
                ),
                (
                    "time_spent_in_live_classes",
                    models.DurationField(default=datetime.timedelta(0)),
                ),
                (
                    "time_spent_in_recording_classes",
                    models.DurationField(default=datetime.timedelta(0)),
                ),
                ("total_classes", models.IntegerField(default=0)),
                ("classes_attended", models.IntegerField(default=0)),
                (
                    "total_time_spent",
                    models.DurationField(default=datetime.timedelta(0)),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.course"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "course"], name="reports_use_user_id_4453c0_idx"
                    ),
                    models.Index(
                        fields=["last_updated"], name="reports_use_last_up_c19d72_idx"
                    ),
                ],
                "unique_together": {("user", "course")},
            },
        ),
        migrations.CreateModel(
            name="DailyAggregation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("type_of_aggregation", models.CharField(max_length=100)),
                ("time_spent", models.DurationField(default=datetime.timedelta(0))),
                ("reference_id", models.IntegerField(null=True)),
                ("resource_name", models.CharField(max_length=500, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.course"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user_id", "date"],
                        name="reports_dai_user_id_42df36_idx",
                    ),
                    models.Index(
                        fields=["type_of_aggregation"],
                        name="reports_dai_type_of_8dd4eb_idx",
                    ),
                ],
                "unique_together": {
                    (
                        "user",
                        "date",
                        "type_of_aggregation",
                        "course",
                        "reference_id",
                        "resource_name",
                    )
                },
            },
        ),
    ]
