# Generated by Django 4.2.16 on 2024-11-10 14:36

import custom_auth.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('form_name', models.CharField(max_length=100, unique=True)),
                ('form_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_data', models.JSONField(blank=True, null=True)),
                ('onboarding_complete', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('institute_roll_number', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('languages', models.TextField(blank=True, default=None, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('country', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('interests', models.TextField(blank=True, default=None, null=True)),
                ('daily_streak', models.IntegerField(blank=True, default=0, null=True)),
                ('longest_streak', models.IntegerField(blank=True, default=0, null=True)),
                ('last_task_date', models.DateField(blank=True, null=True)),
                ('total_chat_count', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('otp', models.IntegerField(default=custom_auth.models.generate_random_number)),
                ('cv_details', models.JSONField(blank=True, null=True)),
                ('cv_score', models.IntegerField(blank=True, null=True)),
                ('form_response', models.JSONField(blank=True, null=True)),
                ('activity_dates', models.JSONField(default=list)),
                ('doubt_solving_uuid', models.UUIDField(default=None, editable=False, null=True, unique=True)),
                ('doubt_solving_mapping_created', models.BooleanField(default=False)),
                ('doubt_solving_token', models.CharField(blank=True, max_length=8, null=True)),
                ('token_expiration_time', models.DateTimeField(blank=True, null=True)),
                ('form_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='custom_auth.form', to_field='form_name')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
