"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from decouple import config
from django.utils.translation import gettext_lazy as _
from attr.converters import to_bool
from pathlib import Path
import ssl
from ast import literal_eval

from attr.converters import to_bool

# if os.environ["ENV"] == "dev":
from dotenv import load_dotenv

load_dotenv()


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    "SECRET_KEY", default="o!ld8nrt4vc*h1zoey*wj48x*q0#ss12h=+zh)kk^6b3aygg=!"
)


ALLOWED_HOSTS = ["127.0.0.1", "adilmohak1.pythonanywhere.com", "localhost"]

LOCAL_MEM_CACHE = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-snowflake",
    }
}

DEBUG = config("DEBUG", default=False, cast=bool)
ENV = os.environ["ENV"]

CACHES = LOCAL_MEM_CACHE
if ENV in ["local", "staging"]:
    REDIS_URL = (
        f"redis://{os.environ['REDIS_USER']}:{os.environ['REDIS_PASSWORD']}@{os.environ['REDIS_HOST']}:{os.environ['REDIS_PORT']}/"
        f"{os.environ['REDIS_DB']}"
    )
else:
    REDIS_URL = (
        f"rediss://{os.environ['REDIS_USER']}:{os.environ['REDIS_PASSWORD']}@{os.environ['REDIS_HOST']}:{os.environ['REDIS_PORT']}/"
        f"{os.environ['REDIS_DB']}"
    )

if os.environ.get("REDIS_CACHE_ENABLED", False) == "True":
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                "PASSWORD": os.environ["REDIS_PASSWORD"],
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
        }
    }

CACHE_TTL = 60 * 60
CACHE_ENABLED = os.environ.get("CACHE_ENABLED", False)

SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"
SESSION_CACHE_ALIAS = "default"

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True


STORAGE_ACCOUNT_NAME = os.environ.get("STORAGE_ACCOUNT_NAME", "stspeechaistage")
STORAGE_ACCOUNT_KEY = os.environ.get("STORAGE_ACCOUNT_KEY")

### SERVICE SETTINGS
## WHISPER-TIMESTAMP SERVICE
WHISPER_TIMESTAMP_SERVICE_ENDPOINT = os.environ["WHISPER_TIMESTAMP_SERVICE_ENDPOINT"]
WHISPER_TIMESTAMP_SERVICE_AUTH_TOKEN = os.environ[
    "WHISPER_TIMESTAMP_SERVICE_AUTH_TOKEN"
]

## CEFR_LEVEL_SERVICE
CEFR_LEVEL_SERVICE_ENDPOINT = os.environ["CEFR_LEVEL_SERVICE_ENDPOINT"]
CEFR_LEVEL_SERVICE_AUTH_TOKEN = os.environ["CEFR_LEVEL_TIMESTAMP_SERVICE_AUTH_TOKEN"]

PRONUNCIATION_SERVICE_ENDPOINT = os.environ["PRONUNCIATION_SERVICE_ENDPOINT"]
PRONUNCIATION_SERVICE_AUTH_TOKEN = os.environ["PRONUNCIATION_SERVICE_AUTH_TOKEN"]

AZURE_TEXT_ANALYTICS_CLIENT_KEY = os.environ["AZURE_TEXT_ANALYTICS_CLIENT_KEY"]
AZURE_TEXT_ANALYTICS_CLIENT_ENDPOINT = os.environ[
    "AZURE_TEXT_ANALYTICS_CLIENT_ENDPOINT"
]

DEEPGRAM_KEY = os.environ["DEEPGRAM_KEY"]

ANYMAIL = {
    "MAILJET_API_KEY": os.environ["MAILJET_API_KEY"],
    "MAILJET_SECRET_KEY": os.environ["MAILJET_SECRET_KEY"],
}

EMAIL_BACKEND = "anymail.backends.mailjet.EmailBackend"
DEFAULT_FROM_EMAIL = "speechai0@gmail.com"
SERVER_EMAIL = DEFAULT_FROM_EMAIL

ADMINS = os.environ["ADMINS"]
if ADMINS:
    ADMINS = literal_eval(ADMINS)

REFERRAL_URL = os.environ.get("REFERRAL_URL")
FEEDBACK_FORM_URL = os.environ.get("FEEDBACK_FORM_URL")

# Word of the day cache TTL - 1 day in seconds
WORD_OF_DAY_CACHE_TTL = 86400


CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", REDIS_URL)


CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", REDIS_URL)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"

CELERY_TASK_ROUTES = {
    "evaluation.tasks.*": {"queue": "evaluation_queue"},
    "services.tasks.*": {"queue": "services_queue"},
}

CELERY_USE_SSL = not (os.environ.get("CELERY_USE_SSL", "TRUE") == "FALSE")
if CELERY_USE_SSL:
    BROKER_USE_SSL = {"ssl_cert_reqs": ssl.CERT_NONE}
    CELERY_d_BACKEND_USE_SSL = {"ssl_cert_reqs": ssl.CERT_NONE}

# change the default user models to our custom model
AUTH_USER_MODEL = "accounts.User"

# Application definition

DJANGO_APPS = [
    "modeltranslation",  # Translation
    "jet.dashboard",
    "jet",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
]

# Third party apps
THIRD_PARTY_APPS = [
    "crispy_forms",
    "crispy_bootstrap5",
    "django_filters",
    "django_extensions",
]

# Custom apps
PROJECT_APPS = [
    "core.apps.CoreConfig",
    "accounts.apps.AccountsConfig",
    "course.apps.CourseConfig",
    "result.apps.ResultConfig",
    "search.apps.SearchConfig",
    "quiz.apps.QuizConfig",
    "payments.apps.PaymentsConfig",
    "meetings.apps.MeetingsConfig",
]

# apps from speechai
INTEGRATED_APPS = [
    "evaluation",
    "ai_learning",
    "data_repo",
    "services",
    "common",
    "OpenAIService",
    "practice",
    "custom_auth",
]

# Combine all apps
INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + PROJECT_APPS + INTEGRATED_APPS

REST_FRAMEWORK = {
    "EXCEPTION_HANDLER": "accounts.exceptions.custom_exception_handler",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "accounts.authentication.FirebaseAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # whitenoise to serve static files
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "accounts.auth_context_processor.firebase_config",
                # 'django.template.context_processors.i18n',
                # 'django.template.context_processors.media',
                # 'django.template.context_processors.static',
                # 'django.template.context_processors.tz',
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ATOMIC_REQUESTS": True,
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ["POSTGRES_DB"],
        "USER": os.environ["POSTGRES_USER"],
        "PASSWORD": os.environ["POSTGRES_PASSWORD"],
        "HOST": os.environ["POSTGRES_HOST"],
        "PORT": os.environ["POSTGRES_PORT"],
    }
}

# https://docs.djangoproject.com/en/stable/ref/settings/#std:setting-DEFAULT_AUTO_FIELD
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/


def gettext(s):
    return s


LANGUAGES = (
    ("en", gettext("English")),
    ("fr", gettext("French")),
    ("es", gettext("Spanish")),
    ("ru", gettext("Russia")),
)

LOCALE_PATHS = (os.path.join(BASE_DIR, "locale"),)

MODELTRANSLATION_DEFAULT_LANGUAGE = "en"
LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

# https://docs.djangoproject.com/en/dev/ref/settings/#static-url
STATIC_URL = "/static/"
# https://docs.djangoproject.com/en/dev/ref/contrib/staticfiles/#std:setting-STATICFILES_DIRS
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
# https://docs.djangoproject.com/en/dev/ref/settings/#static-root
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
# https://docs.djangoproject.com/en/dev/ref/contrib/staticfiles/#staticfiles-finders
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]


# Media files config
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# -----------------------------------
# E-mail configuration

EMAIL_BACKEND = config(
    "EMAIL_BACKEND", default="django.core.mail.backends.smtp.EmailBackend"
)
EMAIL_HOST = config("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = config("EMAIL_PORT", default=587)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
EMAIL_FROM_ADDRESS = config("EMAIL_FROM_ADDRESS")
EMAIL_USE_SSL = False

# crispy config
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# Strip payment config
STRIPE_SECRET_KEY = config("STRIPE_SECRET_KEY", default="")
STRIPE_PUBLISHABLE_KEY = config("STRIPE_PUBLISHABLE_KEY", default="")


# LOGGING
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/dev/ref/settings/#logging
# See https://docs.djangoproject.com/en/dev/topics/logging for
# more details on how to customize your logging configuration.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "%(levelname)s %(asctime)s %(module)s "
            "%(process)d %(thread)d %(message)s"
        }
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        }
    },
    "root": {"level": "INFO", "handlers": ["console"]},
}

# WhiteNoise configuration
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

STUDENT_ID_PREFIX = config("STUDENT_ID_PREFIX", "ugr")
LECTURER_ID_PREFIX = config("LECTURER_ID_PREFIX", "lec")


# Constants
YEARS = (
    (1, "1"),
    (2, "2"),
    (3, "3"),
    (4, "4"),
    (5, "5"),
    (6, "6"),
)

BACHELOR_DEGREE = "Bachelor"
MASTER_DEGREE = "Master"

LEVEL_CHOICES = (
    (BACHELOR_DEGREE, _("Bachelor Degree")),
    (MASTER_DEGREE, _("Master Degree")),
)

FIRST = "First"
SECOND = "Second"
THIRD = "Third"

SEMESTER_CHOICES = (
    (FIRST, _("First")),
    (SECOND, _("Second")),
    (THIRD, _("Third")),
)


AI_BOT_USERNAME = os.environ[
    "AI_BOT_USERNAME"
]  ##For staging - "BlendnetAILearningStagingBot"
AI_TELEGRAM_BOT_TOKEN = os.environ["AI_TELEGRAM_BOT_TOKEN"]
DEFAULT_AGENT_CONFIG_NAME = os.environ["DEFAULT_AGENT_CONFIG_NAME"]
ALLOWED_TELEGRAM_USERNAMES = []
BUFFER_DURATION_MINUTES = os.getenv("BUFFER_DURATION_MINUTES", 2)
SPEADSHEET_ID = os.environ["SPEADSHEET_ID"]
TESTS_SUBSHEET_NAME = os.environ["TESTS_SUBSHEET_NAME"]
USERS_SUBSHEET_NAME = os.environ["USERS_SUBSHEET_NAME"]
XOBIN_API_KEY = os.environ["XOBIN_API_KEY"]
XOBIN_ENDPOINT = os.environ["XOBIN_ENDPOINT"]
RESUME_STORAGE_CONTAINER_NAME = os.environ["RESUME_STORAGE_CONTAINER_NAME"]
IDENTITY_TOOLKIT_API_URL = os.environ["IDENTITY_TOOLKIT_API_URL"]
RESUME_APP_BACKEND_URL = os.environ["RESUME_APP_BACKEND_URL"]
GITHUB_API_BASE_URL = os.environ["GITHUB_API_BASE_URL"]
GITHUB_API_TOKEN = os.environ["GITHUB_API_TOKEN"]
ADMIN_FIREBASE_ACCOUNT_ID = os.environ["ADMIN_FIREBASE_ACCOUNT_ID"]
USER_IDS_CODING_TEST_ENABLED = os.environ["USER_IDS_CODING_TEST_ENABLED"]
AZURE_OPENAI_API_KEY = os.environ["AZURE_OPENAI_API_KEY"]
AZURE_OPENAI_API_VERSION = os.environ["AZURE_OPENAI_API_VERSION"]
AZURE_OPENAI_AZURE_ENDPOINT = os.environ["AZURE_OPENAI_AZURE_ENDPOINT"]

TEST_EVALUATION_WAITING_TIME_IN_SECONDS = os.environ.get(
    "TEST_EVALUATION_WAITING_TIME_IN_SECONDS", 240
)  # 4 minutes
DSA_FLOW_TEST_QUESTION_ID = os.environ.get("DSA_FLOW_TEST_QUESTION_ID")

AZURE_OPENAI_API_KEY_OLD = os.environ["AZURE_OPENAI_API_KEY_OLD"]
AZURE_OPENAI_AZURE_ENDPOINT_OLD = os.environ["AZURE_OPENAI_AZURE_ENDPOINT_OLD"]

GLOT_KEY = os.environ["GLOT_KEY"]
GLOT_URL = os.environ["GLOT_URL"]

SELF_HOSTED_GLOT_KEY = os.environ["SELF_HOSTED_GLOT_KEY"]
SELF_HOSTED_GLOT_URL = os.environ["SELF_HOSTED_GLOT_URL"]

SENDGRID_KEY = os.environ.get("SENDGRID_KEY")
CREDS_EMAIL_TEMPLATE_ID = os.environ.get("CREDS_EMAIL_TEMPLATE_ID")
PASSWORD_EMAIL_TEMPLATE_ID = os.environ.get("PASSWORD_EMAIL_TEMPLATE_ID")

DSA_GLOBAL_SHEET_ID = os.environ.get("DSA_GLOBAL_SHEET_ID")
DSA_METRICS_SHEET_ID = os.environ.get("DSA_METRICS_SHEET_ID")
BACKEND_BASE_URL = os.environ.get("BACKEND_BASE_URL")

LLM_CONFIGS_PATH = str(BASE_DIR) + "/llm_configs_v2/"
DISABLE_PROMPT_VALIDATIONS = to_bool(
    os.environ.get("DISABLE_PROMPT_VALIDATIONS", "FALSE")
)

import litellm


LANGFUSE_PUBLIC_KEY = os.environ.get("LANGFUSE_PUBLIC_KEY")
LANGFUSE_SECRET_KEY = os.environ.get("LANGFUSE_SECRET_KEY")
LANGFUSE_SAMPLE_RATE = os.environ.get("LANGFUSE_SAMPLE_RATE", 1)

LANGFUSE_HOST = os.environ.get("LANGFUSE_HOST", "https://us.cloud.langfuse.com")

if LANGFUSE_SECRET_KEY and LANGFUSE_PUBLIC_KEY:
    litellm.success_callback = ["langfuse"]
    litellm.failure_callback = ["langfuse"]

DOUBT_SOLVING_ORG_API_KEY = os.environ.get("DOUBT_SOLVING_ORG_API_KEY")

import firebase_admin
from firebase_admin import credentials

FIREBASE_API_KEY = os.environ["FIREBASE_API_KEY"]
FIREBASE_UNIVERSE_DOMAIN = os.environ["FIREBASE_UNIVERSE_DOMAIN"]
FIREBASE_ACCOUNT_TYPE = os.environ["FIREBASE_ACCOUNT_TYPE"]
FIREBASE_PROJECT_ID = os.environ["FIREBASE_PROJECT_ID"]
FIREBASE_PRIVATE_KEY_ID = os.environ["FIREBASE_PRIVATE_KEY_ID"]
FIREBASE_PRIVATE_KEY = os.environ["FIREBASE_PRIVATE_KEY"]
FIREBASE_CLIENT_EMAIL = os.environ["FIREBASE_CLIENT_EMAIL"]
FIREBASE_CLIENT_ID = os.environ["FIREBASE_CLIENT_ID"]
FIREBASE_AUTH_URI = os.environ["FIREBASE_AUTH_URI"]
FIREBASE_TOKEN_URI = os.environ["FIREBASE_TOKEN_URI"]
FIREBASE_AUTH_PROVIDER_X509_CERT_URL = os.environ[
    "FIREBASE_AUTH_PROVIDER_X509_CERT_URL"
]
FIREBASE_CLIENT_X509_CERT_URL = os.environ["FIREBASE_CLIENT_X509_CERT_URL"]
FIREBASE_AUTH_DOMAIN = os.environ["FIREBASE_AUTH_DOMAIN"]
FIREBASE_STORAGE_BUCKET = os.environ["FIREBASE_STORAGE_BUCKET"]
FIREBASE_MESSAGING_SENDER_ID = os.environ["FIREBASE_MESSAGING_SENDER_ID"]
FIREBASE_APP_ID = os.environ["FIREBASE_APP_ID"]
FIREBASE_MEASUREMENT_ID = os.environ["FIREBASE_MEASUREMENT_ID"]

if not firebase_admin._apps:
    cred = credentials.Certificate(
        {
            "type": FIREBASE_ACCOUNT_TYPE,
            "project_id": FIREBASE_PROJECT_ID,
            "private_key_id": FIREBASE_PRIVATE_KEY_ID,
            "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDVqZ1RAgoIA/8k\n6DstVSmrxZgCNLr8YN9SsbPScLpq7yHGCcQ2fmOvu71U9JIrL/dJzkMJT3WPo61c\nYG7OkQ07Sgd/XGr28REHw4Ri1tFZ68mIeFMYSjd5uyVax1g1L08MUOVfJbd/IfBa\nbIFjqvpHkx6igNcp+bygI4PHNsBvM5eO1SJbEwvKZj82RdMfn/KmBrRsm0j8D0gP\nv2L4kCvzxaEM3W9jeVJkwrA+sMF2RgWMiAxvezb0xy20Xk3M6SV+RYEK41YB+VHc\neJG3RhiEooLSL3HHif7HU3Rt/p4sDVd7oBq0PxEOHUxpa1conwsXVH/cmto8Glvs\nG5bG5tOzAgMBAAECggEACKobML4gwq3JeqlW6ldfcZF5a5rQe7brTNgwpE0L/OrQ\n93iilgR5bcFIQ+9dv2tE35+sr5j4TyiNDtzzlrmNIXq2uR8kpfpP/XzxRmzTCo7O\n774paH0XU37CXLRkIFatzEsPh38+ZLpvRnYgp8u24JDXwjFFXcoR2yX1jG5CTtVk\nHsDcp6jnWRYO2bPfA5E2uOLSV3fWlg7IL0ec/lS4dDoFtzpFhk3fTd57sJGY97JV\nAHvemV6IGGv5p1Ypy+Jku3PlgxHtlE8P1gnwKXPgnfJ+eRWYjkZ2Ulo8jF6EmZ5i\n2T5H5rnR1YnW9m3buro2cBTj0z6bMCWJMtA/giroeQKBgQDzGVz7HEjrpb40hZmc\n6SDjaInaY+k2tgMuUZ1qTmBmqratI3VZuzMU8Rf1dTTQwvo29/Nw2h1c4Pz1R9g8\n9d0V9YFE3kvMWwoRDaxLMNLtfeEXloo/9XoIehwtlELuXsFRR8FD+6c1GwPMmTeK\na2bwmcXHXphqrixkMQNXxqRN7wKBgQDhAFb6Z2KLEKVZy8yKQzB2ZQ6aC9MrfRwZ\namneJg5d1lqCYnTSyMtFR3Erc0cSACJ6/Om4EpvXKPFJ/UD0rSjVqF1lNj8MeIpa\nzk5Tv5EeVA/RswR+qxTAw0G4tnCOXS0G2S8Ygq2TIB1mfGqwloCGJ1Chz44pa+Og\nrvqcdeWafQKBgQDiqqyCy13GsxUFveh8YPc0cv3Obsg+JjoTDzBatde3Asgv6db6\nosy/Ywl26iEj4hkR9eG8QPON7Y6PWbzrIkhRuEcfIrLEScK6Ieibd1vE61FdABXK\nCyYND2aErTA3OIzCL8ipjdTbdGP3eolJ/FjQUGEUQ0SUe/CSPw0h4+rBawKBgQCt\n5C9Uk3ZLd+/y+Fj6OndH6U5hq+XmZGjFE8MCV3Me/r0wq5sSFPFUd6R1KkCxHr2H\nQ9P12RvsK85fmoULFJDMn7Setk//+WEkUPGkNBeZ0unu7WX554rAd6dhdE6FGGnm\nMw/853HylQ1j2aAzHf3ysIvWoqyCQsnHs7QoG835mQKBgQDFqZ4Q6jjw3LADysvQ\n+SAlU5k/XG3kDEIhgNo3ZT+QnOdMKhscHlT8j8NObTMSSclnC0ZF243WpzNm6/l/\n16Utzeo3wdxwkwFWdUvuZMhtJ5lmxnhczmXxV56nQf/Y0/+pniw6SQ6uVstTTzfA\nfj6v7eeibQw6Z/qur3MmPf3SlA==\n-----END PRIVATE KEY-----\n".replace(
                "\\n", "\n"
            ),
            "client_email": FIREBASE_CLIENT_EMAIL,
            "client_id": FIREBASE_CLIENT_ID,
            "auth_uri": FIREBASE_AUTH_URI,
            "token_uri": FIREBASE_TOKEN_URI,
            "auth_provider_x509_cert_url": FIREBASE_AUTH_PROVIDER_X509_CERT_URL,
            "client_x509_cert_url": FIREBASE_CLIENT_X509_CERT_URL,
            "universe_domain": FIREBASE_UNIVERSE_DOMAIN,
        }
    )
    firebase_admin.initialize_app(cred)
