# Generated by Django 4.2.16 on 2024-11-10 14:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('user_id', models.IntegerField(editable=False, help_text='Unique ID of the user who attempted.', null=True)),
                ('daily_streak', models.IntegerField(default=0, help_text='Count of daily continuos streak including this attempt')),
                ('attempt_status', models.CharField(choices=[('NA', 'Not Attempted'), ('AC', 'Attempt Completed'), ('AS', 'Attempt Started')], default='NA', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAttemptedQuestionResponse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this particular User  Question Response.', primary_key=True, serialize=False)),
                ('question_text', models.TextField(blank=True, help_text='Text of the attempted question.', max_length=1000, null=True)),
                ('question_type', models.CharField(blank=True, choices=[('IL', 'IELTS'), ('IP', 'Interview Prep'), ('CQ', 'Custom question entered by the user')], help_text='Type of the attempted question.', max_length=2, null=True)),
                ('audio_filename', models.CharField(default='audio.wav', help_text='Audio file name as submitted', max_length=100)),
                ('additional_meta', models.JSONField(blank=True, help_text='This field is used to store additional metadata related to the User Attempted Question Response.', null=True)),
                ('evaluation_id', models.UUIDField(editable=False, help_text='Unique ID for evaluation of this particular repsonse.')),
                ('evaluation_score', models.DecimalField(blank=True, decimal_places=2, help_text='Cummulative score of evaluation', max_digits=4, null=True)),
                ('evaluation_data', models.JSONField(blank=True, help_text='This field is used to store additional metadata related to the user response evaluation.', null=True)),
                ('user_question_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response', to='practice.userquestionattempt')),
            ],
            options={
                'verbose_name': 'User Attempted Question Response',
                'verbose_name_plural': 'User Attempted Question Responses',
            },
        ),
    ]
