# Generated by Django 4.2.16 on 2025-02-03 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_template', models.TextField()),
                ('variables', models.JSONField()),
                ('user_ids', models.JSONField()),
                ('medium', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('notification_type', models.CharField(choices=[('meeting_24h', 'Meeting 24 Hour Reminder'), ('meeting_30m', 'Meeting 30 Minute Reminder'), ('user_inactive_past_7_days', 'User 7 Days Inactive Notification'), ('missed_lecture', 'Missed Lecture Notification'), ('assessment_pending', 'Assessment Pending')], max_length=100)),
                ('reference_id', models.IntegerField(null=True)),
                ('timing_type', models.CharField(choices=[('immediate', 'Immediate'), ('scheduled', 'Scheduled')], default='scheduled', max_length=20)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('picked', 'Picked for Processing'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telegram_chat_id', models.CharField(max_length=255, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('medium', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationintent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
